### PR TITLE
add seo and twitter cards to index.js layouts

### PR DESCRIPTION
**Pull request by dunphyben**

### CODE REVIEW

**Comment by dunphyben** [comment]
@DSofter Please review

**Comment by dunphyben** [comment]
Looks like the `<link rel>`'s are not getting added:

image

I was unable to get them to work inside the `<helmet`. 

Here they are on the production site:

image

So @DSofter if you can move the `<link rel>`'s into the `<helmet>` then we should be good to go

**Comment by DSofter** [comment]
@dunphyben Please double check

**Comment by dunphyben** [comment]
@DSofter Netlify build is failing

image

**Comment by dunphyben** [comment]
is there a reason that you added `key={index}` to `src/components/ticket-widget/index.js` in your commit?

**Pull request merged**
