### PR TITLE
More UI polish

### PR DESCRIPTION
**Pull request by DSofter**
## Screenshots

**Main Page (desktop)**
frontier sf

**Main Page (mobile)**
frontier sf 1

**About the Organizers (desktop)**
frontier sf 2

**About the Organizers (mobile)**
frontier sf 3

**Code of Conduct (desktop)**
frontier sf 8

**Code of Conduct (mobile)**
frontier sf 4

**Free Educational Resource (desktop)**
frontier sf 7

**Free Educational Resource (mobile)**
frontier sf 6

## Reviewers
@prashanthr @dunphyben

### CODE REVIEW

**Comment by dunphyben** [comment]
Looks good!

**Comment by prashanthr** [comment]
@DSofter Thanks for the changes
Branch looks good on local

1) The links in the top nav menu stay highlighted with an underline after clicking on them
screen shot 2017-12-06 at 3 51 34 pm
2) Do you know why the deploy preview looks messed up? Is some CDN stuff overriding the styles?
screen shot 2017-12-06 at 3 51 57 pm

**Comment by DSofter** [comment]
@prashanthr Looks like the css is missing. Is that something you can check?

**Comment by prashanthr** [comment]
@DSofter I was able to reproduce the style issues on local. I think the bootstrap styles were missing. It's not easy to dynamically wire via html.js. I've been down that path. Hence I've included it in the root layout. Now the deploy preview looks okay but the local environment does not. It's a bit of a tricky situation. But see if you can figure it out. We should expect consistent results. So I'm not merging this right now. I'd suggest we go through small issues and make small pull requests on the existing develop branch to fix specific issues.

screen shot 2017-12-10 at 11 34 40 am

**Comment by prashanthr** [comment]
@DSofter Can we close and delete this PR?

**Comment by prashanthr** [comment]
Closing because PR is stale.

**Pull request closed without merging**
